# Configuración de Agentes del Sistema

agents:
  router:
    name: "Query Router Agent"
    description: "Clasifica la intención de la consulta del usuario"
    model: "gpt-4-turbo-preview"
    temperature: 0
    max_tokens: 500
    system_prompt: |
      Eres un agente clasificador experto. Tu tarea es analizar la pregunta del usuario
      y determinar:
      1. Tipo de consulta: "simple_qa", "comparison", "code_generation", "summary"
      2. Si necesita búsqueda en la base de conocimiento (needs_rag: true/false)
      3. Complejidad: "low", "medium", "high"
      
      Responde SIEMPRE en formato JSON.

  rag:
    name: "RAG Agent"
    description: "Busca información relevante en la base de conocimiento"
    top_k: 5
    similarity_threshold: 0.7
    rerank: true
    chunk_overlap_check: true
    metadata_filter: null  # Puede filtrar por source, date, etc.

  synthesis:
    name: "Synthesis Agent"
    description: "Genera respuestas coherentes basadas en el contexto"
    model: "gpt-4-turbo-preview"
    temperature: 0.3
    max_tokens: 1500
    system_prompt: |
      Eres un asistente experto en documentación técnica. Tu tarea es:
      1. Sintetizar la información del contexto proporcionado
      2. Responder de forma clara y concisa
      3. SIEMPRE citar las fuentes usando [source: filename, page: X]
      4. Si no tienes información suficiente, admítelo
      
      Genera respuestas en formato JSON con: answer, sources, confidence (0-1)

  validator:
    name: "Validator Agent"
    description: "Valida la calidad y formato de las respuestas"
    required_fields:
      - "answer"
      - "sources"
      - "confidence"
    min_sources: 1
    min_confidence: 0.6
    check_hallucination: true

# Workflow Configuration
workflow:
  max_iterations: 3  # Máximo de reintentos si falla validación
  timeout_seconds: 60
  enable_logging: true
  save_intermediate_states: true